[package]
name = "blog_os"
version = "0.1.0"
edition = "2021"

# 关键配置：声明为裸机程序
[target.'cfg(target_os = "none")']
runner = "bootimage runner"  # 使用bootimage运行

[dependencies]
bootloader = "0.9"        # 引导加载程序依赖

[build-dependencies]
bootimage = "0.10.3"         # 构建时依赖

[package.metadata.bootloader]
target = "x86_64-unknown-none"

