[package]
name = "blog_os"
version = "0.1.0"
edition = "2021"

# [package.metadata.bootloader]
# target configuration moved to command line arguments

[dependencies]
bootloader = "0.9.8"

[build-dependencies]
bootimage = "0.10.3"         # 构建时依赖

# 配置构建标准库
[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[unstable]
build-std = ["core", "compiler_builtins"]

[target.'cfg(target_os = "none")']
runner = "bootimage runner"


