[unstable]
build-std = ["core", "alloc", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]

[build]
target = "x86_64-blog_os.json"
rustflags = ["-C", "relocation-model=static"]

[target.'x86_64-blog_os.json']
runner = "bootimage runner"